/**
 * TIF Threat Categories
 */

module.exports = {
    DRIFT_ANOMALY: "DRIFT_ANOMALY",
    GOVERNANCE_ABUSE: "GOVERNANCE_ABUSE",
    SAFETY_ALERT: "SAFETY_ALERT",
    XRPL_EVENT_COLLISION: "XRPL_EVENT_COLLISION",
    EVM_EVENT_COLLISION: "EVM_EVENT_COLLISION",
    CLEARANCE_VIOLATION: "CLEARANCE_VIOLATION",
    COMPLIANCE_FLAG: "COMPLIANCE_FLAG",
    UNKNOWN: "UNKNOWN"
};
