"use strict";

/**
 * Canonical MODLINK denial reasons
 * CJS-only. NO dynamic imports. NO ESM.
 */

const DENY_REASONS = Object.freeze({
    MISSING_PROOF: "DENY_MISSING_MODLINK_PROOF",
    MALFORMED_PROOF: "DENY_MALFORMED_MODLINK_PROOF",
    INVALID_PROOF: "DENY_INVALID_MODLINK_PROOF",
    ACTION_MISMATCH: "DENY_ACTION_MISMATCH",
    POLICY_DENY: "DENY_POLICY",
    TIMELOCK_NOT_SATISFIED: "DENY_TIMELOCK_NOT_SATISFIED"
});

module.exports = { DENY_REASONS };

